server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 112372
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#===================== redis====================
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
